### PR TITLE
DWC2 Vbus sensing enhancement

### LINKED ISSUE #1476: No DCD_EVENT_UNPLUGGED event for STM32 FSdev
### Operating System

Windows 10

### Board

Custom based on STM32H7B3

### Firmware

portable/st/stm32_fsdev/dcd_stm32_fsdev.c

### What happened ?

Dear,

I have followed the example for CDC/MSC using FreeRTOS and have got pretty much everything working. Expect for the disconnection event: unmount callback (tud_umount_cb) is not being called for this platform and driver. Mount callback (tud_mount_cb) happens as expected.

I am new to this library, so maybe I have messed up something, but as everything else is working, I guess I maybe facing a bug somewhere. Looking into the code, the old synopsys driver evokes the DCD_EVENT_UNPLUGGED event, but the new stm32_fsdev does not.

Any help would be much appreciated.

### How to reproduce ?

Just connect the board using the new stm32_fsdev and look for the mount and unmount callbacks.

### Debug Log as txt file

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by HiFiPhile**
**Describe the PR**
- Add VBus sensing option to `tud_configure()`, for STM32 `GCCFG` register config is now included in the stack, which reduces BSP compicity.
- Also turn off device mode Vbus output in F4/F7's BSP to fix disconnection detection.
- Add Vbus detection support to Nucleo-U5A5AZJ which uses ADC to read Vbus voltage.
- Also fix N6 BSP to make both ports work

Other device families should not be infected as `GOTGCFG` default value stays the same.

Device and host modes are tested and functional:
| Board | Type | Disconnection detection |
|--------|--------|--------|
| F407-DISCO | Internal FS | OK |
| F723E-DISCO | Internal FS / Internal ULPI HS | Both ports OK [1](#1) |
| H747I-DISCO | External ULPI HS | OK |
| Nucleo-H7S3L8 | Internal UTMI HS | NO Vbus connection |
| Nucleo-U5A5AZJ | Internal UTMI HS | OK | 
| N6570DK | Internal UTMI HS | NO Vbus connection |

1: Needs 104cf33239eda282b34c1f7971fbfc8e310eabf8

Should fix #1476, #3426

**Additional context**
No more callback is needed for #3378

### CODE REVIEW

**Comment by HiFiPhile** [comment]
@brentmellor  Could you check if Vbus detection works on Nucleo-U575 ?

**Comment by brentmellor** [comment]
@HiFiPhile 
I'll try to check this code sometime this week. I modified the development board trying to get VBUS detection working natively and so I'll need to put things back to original state.

File: src/portable/synopsys/dwc2/dwc2_stm32.h [hunk 1]
```diff
@@ -300,6 +303,136 @@ static inline void dwc2_phy_update(dwc2_regs_t* dwc2, uint8_t hs_phy_type) {
...
+static inline void dwc2_stm32_gccfg_cfg(dwc2_regs_t* dwc2, bool vbus_sensing, bool is_host) {
+  if (is_host) {
+    vbus_sensing = false;
+  }
+#if CFG_TUSB_MCU == OPT_MCU_STM32F1
+  // F1: Basic FS-only core, no VBUS sensing support
+  // Only PWRDWN bit is used (set in dwc2_phy_init)
+  (void) vbus_sensing;
+
+#elif CFG_TUSB_MCU == OPT_MCU_STM32F2 || CFG_TUSB_MCU == OPT_MCU_STM32F4
```
Comment (hathach) [inline src/portable/synopsys/dwc2/dwc2_stm32.h]: f412 (3.20a) has VBDEN, I think we should use the dwc2 core version instead. I am making the change locally, trying to wrap this up before TET.

Comment (HiFiPhile) [reply src/portable/synopsys/dwc2/dwc2_stm32.h]: I've thought about that, but I don't have all boards to ensure the correspondence between core version and ST's customization.

Comment (hathach) [reply src/portable/synopsys/dwc2/dwc2_stm32.h]: I have changed to use the GUID instead, which is ST internal dwc2 configuration I guess. I don't have all the boards as well, we will rely on the dwc2_info.py/md. And implement the best we could. Anything else would require PRs.

File: src/portable/synopsys/dwc2/dwc2_stm32.h [hunk 2]
```diff
@@ -300,6 +303,66 @@ static inline void dwc2_phy_update(dwc2_regs_t* dwc2, uint8_t hs_phy_type) {
   }
 }
 
+//------------- GCCFG configuration -------------//
+static inline void dwc2_stm32_gccfg_cfg(dwc2_regs_t* dwc2, bool vbus_sensing, bool is_host) {
```
Comment (hathach) [inline src/portable/synopsys/dwc2/dwc2_stm32.h:307]: @HiFiPhile I change the function to work based on the GUID. You could check the dwc2_info.md for reference. We can update the logic if needed.

Comment (HiFiPhile) [reply src/portable/synopsys/dwc2/dwc2_stm32.h:307]: Looks good to me !
