### PR TITLE
Fix #3033: Increase array bounds and test for overflow

### LINKED ISSUE #3033: Potential array bounds error for complex MIDI devices
### Operating System

Linux

### Board

pico

### Firmware

examples/host/midi_rx

### What happened ?

Each virtual cable in a USB MIDI device consumes at least one internal jack and one external jack. Although devices with more than a total of 8 virtual cables are not common, they do exist. For example plugging a [MOTU MIDI Express 128](https://motu.com/products/midi/128) would cause https://github.com/hathach/tinyusb/blob/5333d042f9384ec1cc0663a2708c0ca7cb5cdc32/src/class/midi/midi_host.c#L255 to overrun its array bounds.

I recommend one of two solutions:
1. Make the array bounds in `tuh_midi_mount_cb_t` `jack_desc[]` array configurable and check the array bounds before adding a new jack descriptor pointer to the array.
2. The `desc_header`, `desc_element`, `desc_epin`, `desc_epout`, `jack_num` and `desc_jack` members of the `tuh_midi_mount_cb_t` structure are redundant to the other elements in the structure. As a practical matter, if an application has to parse through individual descriptors to find critical information, then it might as well parse the entire MIDI interface descriptor. I am almost ready to release a library that extracts string information from the descriptor that demonstrates this fact.

I will submit a pull request to implement what solution you prefer.

### How to reproduce ?

Code inspection

### Debug Log as txt file (LOG/CFG_TUSB_DEBUG=2)

N/A

### Screenshots

_No response_

### I have checked existing issues, dicussion and documentation

- [x] I confirm I have checked existing issues, dicussion and documentation.

### PR DESCRIPTION
**Pull request by rppicomidi**
**Describe the PR**
See issue #3033

**Additional context**
See issue #3033

### CODE REVIEW

File: src/class/midi/midi_host.c [hunk 1]
```diff
@@ -254,7 +254,8 @@ bool midih_open(uint8_t rhport, uint8_t dev_addr, tusb_desc_interface_t const *d
             TU_LOG_DRV("  Jack %s %s descriptor \r\n",
                        tu_desc_subtype(p_desc) == MIDI_CS_INTERFACE_IN_JACK ? "IN" : "OUT",
                        p_desc[3] == MIDI_JACK_EXTERNAL ? "External" : "Embedded");
-            desc_cb.desc_jack[desc_cb.jack_num++] = p_desc;
+            if (desc_cb.jack_num < TU_ARRAY_SIZE(desc_cb.desc_jack))
```
Comment (hathach) [inline src/class/midi/midi_host.c:257]: can you put an bracket for `if() { }`

**Comment by hathach** [comment]
I also notice at line 594 the statement is out of place, it is either part of default of get the wrong indent, would you mind double checkinging it. Thank you
https://github.com/hathach/tinyusb/blob/4b46493cb4f8699c95e01783eee5cf90ca7810e2/src/class/midi/midi_host.c#L592-L594

image

**Comment by rppicomidi** [comment]
@hathach Good catch on line 594! Yes, that statement is out of place. Will fix it.

**Review by hathach — APPROVED** [review]
perfect, thank you
