### PR TITLE
Fix #3159: Handle MIDI interface after audio streaming interface

### LINKED ISSUE #3159: MIDI class compliant driver not loaded ("device not supported") for Line6 Pod Go (and HX Stomp) USB devices.
### Operating System

Others

### Commit SHA

latest git pull on pico-sdk v 2.1.1

### Board

RPi pico (RP2040) - pico-sdk 2.1.1 on vscode pico plugin

### Firmware

when used in the midi2usbhost project (https://github.com/rppicomidi/midi2usbhost) simple MIDI devices like the Korg NanoKontrol2 are discovered correctly, but Line6 Pod Go is not discovered. usb descriptor and debug output from tinyUSB lib attached below.

### What happened ?

when used in the midi2usbhost project (https://github.com/rppicomidi/midi2usbhost) simple MIDI devices like the Korg NanoKontrol2 are discovered correctly, but Line6 Pod Go is not discovered. usb descriptor and debug output from tinyUSB lib attached below.

This is the usb descriptor for the POD Go (dumped on a linux machine):
[podgo-descriptor.txt](https://github.com/user-attachments/files/21040625/podgo-descriptor.txt)

This is the serial log output when debug level set to 2:
[line6podgo_log.txt](https://github.com/user-attachments/files/21040654/line6podgo_log.txt)

For comparison, this is the log from the same system when a Korg NanoKONTROL2 is plugged in:
[midi2usbhost_log_nanocontrol2.txt](https://github.com/user-attachments/files/21040661/midi2usbhost_log_nanocontrol2.txt)

### How to reproduce ?

update vscode and pico-sdk plugin (to latest - 2.1.1)
cd to .pico-sdk/sdk/2.1.1/lib/tinyusb
run "git checkout master" then "git pull" to ensure tinyusb code is latest
run "git clone --recurse-submodules https://github.com/rppicomidi/midi2usbhost.git"
import midi2usbhost folder into vscode using the pico-sdk "import" function
compile project
flash project to pico board

### Debug Log as txt file (LOG/CFG_TUSB_DEBUG=2)

[line6podgo_log.txt](https://github.com/user-attachments/files/21040831/line6podgo_log.txt)

### Screenshots

_No response_

### I have checked existing issues, dicussion and documentation

- [x] I confirm I have checked existing issues, dicussion and documentation.

### PR DESCRIPTION
**Pull request by rppicomidi**
**Describe the PR**
This pull request handles complex audio/MIDI devices (usually guitar effects processors) where the audio streaming interface follows the audio control interface, which is then followed by a MIDI interface.

**Additional context**
If applicable, add any other context about the PR and/or screenshots here.

### CODE REVIEW

File: src/class/midi/midi_host.c [hunk 1]
```diff
@@ -222,11 +229,20 @@ bool midih_open(uint8_t rhport, uint8_t dev_addr, tusb_desc_interface_t const *d
 
     p_desc = tu_desc_next(p_desc);
     desc_itf = (const tusb_desc_interface_t *)p_desc;
-    TU_VERIFY(TUSB_CLASS_AUDIO == desc_itf->bInterfaceClass);
     p_midi->itf_count = 1;
-  }
+    // See issue #3159
+    while ((p_desc < p_end) && (tu_desc_next(p_desc) <= p_end) && (desc_itf->bDescriptorType != TUSB_DESC_INTERFACE || (desc_itf->bInterfaceClass == TUSB_CLASS_AUDIO && desc_itf->bInterfaceSubClass != AUDIO_SUBCLASS_MIDI_STREAMING)))
```
Comment (hathach) [inline src/class/midi/midi_host.c]: are we skipping until we got TUSB_DESC_INTERFACE/TUSB_DESC_INTERFACE/AUDIO_SUBCLASS_MIDI_STREAMING , can we just use 

```
!(desc_itf->bDescriptorType == TUSB_DESC_INTERFACE && desc_itf->bInterfaceClass == TUSB_CLASS_AUDIO && desc_itf->bInterfaceSubClass == AUDIO_SUBCLASS_MIDI_STREAMING)
```

Comment (rppicomidi) [reply src/class/midi/midi_host.c]: We are skipping all descriptors that are not interface class, and we are skipping all audio interface class descriptors that are not MIDI streaming. If we encounter a different interface class, we break out of the loop and give up. The proposed change will not break out of the loop if, for example, the audio streaming descriptors are followed by a Mass Storage Class interface descriptor.

Comment (hathach) [reply src/class/midi/midi_host.c]: ah right, sorry, I was staying up late.

**Review by hathach — APPROVED** [review]
great, thank you. I just add tu_desc_in_bounds() since it appear more and more in class driver.
