### PR TITLE
nrf5x: Fix race condition during startup

### LINKED ISSUE #1154: NRF5x startup race condition between VBUS interrupt and stack initialization
### Operating System

Linux

### Board

pca10095 should be same for pca10056 or other NRF

### Firmware

TinyUSB 0.12.0

### What happened ?

Board initialization for NRF5x (`board_init()` or equivalent) enables VBUS interrupt.
Later USB stack is initialized in `tusb_init()`.
If VBUS interrupt fires before tusb_init() finishes, it can enable normal USB interrupt before tusb_init() would do it.
Then normal USB interrupt tries to post BUS RESET event and _usbd_q may not be ready yet and that can cause system crash or other unpredictable behavior depending on system used.
Since this a race condition it does not happens all the time but enough to take it seriously.

Same scenario was observed in DA146xx driver when it was work in progress, now it is taken care of there.

### How to reproduce ?

Similar result should be possible with normal examples.
In my case this can be observed when system starts from software reset after DFU finishes so device was connected to VBUS whole time.

### Debug Log

```c
void tusb_hal_nrf_power_event (uint32_t event)
{
...
    case USB_EVT_READY:
...
      // Enable interrupt, priorities should be set by application
      NVIC_ClearPendingIRQ(USBD_IRQn);
      NVIC_EnableIRQ(USBD_IRQn); // <- Enables interrupt before tud_init() calls `dcd_int_enable(rhport);`
...

      // Enable pull up
      NRF_USBD->USBPULLUP = 1; // <- This can trigger BUS reset on bus before tud_init() ends
```
this in turn can start handling bus reset interrupt before tusb_init() ends.
In my case mynewt specific queue used for posting events to USB task is not created yet.
Here is reference stack trace where it's visible that **USBD_IRQHandler** was called before tusb_init() wanted interrupt to be enabled.

```gdb
#0  0x0002a148 in os_memblock_get (mp=mp@entry=0xc) at repos/apache-mynewt-core/kernel/os/src/os_mempool.c:340
#1  0x000326de in osal_queue_send (in_isr=<optimized out>, data=0x2007fda4, qhdl=0x0) at repos/tinyusb/src/osal/osal_mynewt.h:153
#2  dcd_event_handler (event=event@entry=0x2007fda4, in_isr=<optimized out>) at repos/tinyusb/src/device/usbd.c:1132
#3  0x00032768 in dcd_event_bus_reset (rhport=rhport@entry=0 '\000', speed=speed@entry=TUSB_SPEED_FULL, in_isr=in_isr@entry=true) at repos/tinyusb/src/device/usbd.c:1147
#4  0x00033702 in dcd_int_handler (rhport=rhport@entry=0 '\000') at repos/tinyusb/src/portable/nordic/nrf5x/dcd_nrf5x.c:614
#5  0x00028ce4 in USBD_IRQHandler () at repos/apache-mynewt-core/hw/usb/tinyusb/nrf53/src/nrf53.c:41
#6  <signal handler called>
#7  os_mempool_init_internal (mp=0x20003078 <_usbd_qdef+12>, mp@entry=0x2000306c <_usbd_qdef>, blocks=16, block_size=<optimized out>, membuf=<optimized out>, name=name@entry=0x40688 "usbd queue", flags=flags@entry=0 '\000') at repos/apache-mynewt-core/kernel/os/src/os_mempool.c:164
#8  0x0002a0dc in os_mempool_init (mp=mp@entry=0x2000306c <_usbd_qdef>, blocks=<optimized out>, block_size=<optimized out>, membuf=<optimized out>, name=name@entry=0x40688 "usbd queue") at repos/apache-mynewt-core/kernel/os/src/os_mempool.c:184
#9  0x00032458 in osal_queue_create (qdef=0x2000306c <_usbd_qdef>) at repos/tinyusb/src/osal/osal_mynewt.h:129
#10 tud_init (rhport=rhport@entry=0 '\000') at repos/tinyusb/src/device/usbd.c:421
#11 0x00033a4c in tusb_init () at repos/tinyusb/src/tusb.c:41
#12 0x00028c04 in tinyusb_start () at repos/apache-mynewt-core/hw/usb/tinyusb/src/tinyusb.c:63
#13 0x0002680e in sysinit_app () at bin/targets/nordic_pca10095-btshell/generated/src/nordic_pca10095-btshell-sysinit-app.c:98
#14 0x0000e2b4 in main (argc=<error reading variable: value has been optimized out>, argv=<error reading variable: value has been optimized out>) at repos/apache-mynewt-nimble/apps/btshell/src/main.c:2570
#15 0x0002916e in os_main (arg=<optimized out>) at repos/apache-mynewt-core/kernel/os/src/os.c:182
#16 0x00028d58 in tinyusb_hardware_init () at repos/apache-mynewt-core/hw/usb/tinyusb/nrf53/src/nrf53.c:106
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by kasjer**
**Describe the PR**
When NRF5x device is reset by software (after DFU for example),
power event is ready from the beginning.
When power interrupt is triggered before tud_init() finished
USBD_IRQn is enabled before it would be enabled in tud_init().
This in turn may result in BUS RESET event being sent from
USB interrupt to USB task when queue is not initialized yet.
This scenario often happens in Mynewt build where queue creation
takes more time.

To prevent this scenario USBD_IRQn is not enabled in power event
interrupt handler before dcd_init() was called.

**Additional context**
Fixes #1154 

This solution is simple enough but I'm opened to other solutions.

### CODE REVIEW

File: src/portable/nordic/nrf5x/dcd_nrf5x.c [hunk 1]
```diff
@@ -1059,7 +1062,13 @@ void tusb_hal_nrf_power_event (uint32_t event)
...
       // Enable interrupt, priorities should be set by application
       NVIC_ClearPendingIRQ(USBD_IRQn);
-      NVIC_EnableIRQ(USBD_IRQn);
+      // Don't enable USBD interrupt yet, dcd_init() did not finish yet
+      // Interrupt will be enabled by tud_init(), when USB stack is ready
+      // to handle interrupts.
+      if (_dcd.init_called)
+      {
+        NVIC_EnableIRQ(USBD_IRQn);
+      }
```
Comment (hathach) [inline src/portable/nordic/nrf5x/dcd_nrf5x.c:1071]: maybe we should just use the `tud_inited()`. Although dcd shouldn't call higher layer API, i guess it is not that much of dependency. That would be one less variable to worry about.

**Review by hathach — COMMENTED** [review]
great work, thank you for the fix. Though maybe we should use `tud_inited()` . nrf dcd use usbd_defer_func() API to schedule/defer function call anyway :smile:

File: src/portable/nordic/nrf5x/dcd_nrf5x.c (hunk 1 above)
Comment (kasjer) [reply src/portable/nordic/nrf5x/dcd_nrf5x.c:1071]: I did missed that, update is coming...

Comment (kasjer) [reply src/portable/nordic/nrf5x/dcd_nrf5x.c]: Easy way for me to trigger this race (and then verify that solution work) is to have
```c
#define CFG_TUSB_DEBUG              1
```

**Review by hathach — APPROVED** [review]
look great, thank you for the fix

File: src/portable/nordic/nrf5x/dcd_nrf5x.c (hunk 1 above)
Comment (hathach) [reply src/portable/nordic/nrf5x/dcd_nrf5x.c]: thanks for the hint, in this case, the code proves itself :+1:

**Comment by hathach** [comment]
PS: github ci seesm to have network issue, need to re-run the build. will merge when it complete.
