### PR TITLE
Fix host rp2040 with low speed device

### LINKED ISSUE #709: RP2040 Host Stack fails with HID devices
**Set up**
 - **Board**   : Raspberry Pi Pico with UART tracing via Raspberry Pi 4
 - **Firmware**: /examples/host/cdc_msc_hid
 - **Keyboard**: Generic wireless keypad (Exibel - Provision Technology, Inc)
 - **HUB-keyboard**: Apple

**Describe the bug**
When connecting a keyboard to Pico the process fails at the point where the stack is trying to read the full Device Descriptor. If the Device Descriptor fits into one single packet (bMaxPacketSize0 == 64) the reading is successful. When bMaxPacketSize0 == 8 the stack fails.

**To reproduce**
Connect a keyboard to pico

**Log**
Exibel keypad. When the stack is trying to read an 18 bytes long Device Descriptor it fails. Result is PANIC with 'ep 0 in was already available'
[trace-exibel-keypad.txt](https://github.com/hathach/tinyusb/files/6109326/trace-exibel-keypad.txt)

Additional logs added in file src/portable/raspberrypi/rp2040/rp2040_usb.c (pico_trace replaced with TU_LOG2). The stack seems to receive 8 + 8 + 2 bytes but results in PANIC with 'Data Seq Error ':
[trace-exibel-keypad-detailed.txt](https://github.com/hathach/tinyusb/files/6109385/trace-exibel-keypad-detailed.txt)

In comparison a trace with an Apple keyboard-hub. The hub is connecting properly but when trying to read the Device Descriptor of the keyboard behind the hub, the stack fails. Hub bMaxPacketSize0 is 64 which seems to do the trick.
[trace-apple-keyboard-hub.txt](https://github.com/hathach/tinyusb/files/6109426/trace-apple-keyboard-hub.txt)

### PR DESCRIPTION
**Pull request by hathach**
**Describe the PR**
Fix host rp2040 when mounting low speed device (e.g keyboard) with max packet size = 8
- Correct Data Toggle by number of packet: e.g  64 bytes = 8 x 8 bytes --> Data Toggle should not be flipped in the next buffer.  
- Improve RP2040-E4 (host buf sel) fix to prevent panic with already available.

Fix #709, also replace https://github.com/raspberrypi/tinyusb/pull/7 as the fix

### CODE REVIEW

File: src/portable/raspberrypi/rp2040/rp2040_usb.c [hunk 1]
```diff
@@ -126,8 +126,30 @@ void _hw_endpoint_start_next_buffer(struct hw_endpoint *ep)
...
+    // For Host (also device but since we dictate the endpoint size, following scenario does not occur)
+    // Next PID depends on the number of packet in case wMaxPacketSize < 64 (e.g Interrupt Endpoint 8, or 12)
+    // Special case with control status stage where PID is always DATA1
+    if ( ep->transfer_size == 0 )
+    {
+      // ZLP also toggle data
+      ep->next_pid ^= 1u;
+    }else
+    {
+      uint32_t packet_count = 1 + ((ep->transfer_size - 1) / ep->wMaxPacketSize);
```
Comment (kilograham) [inline src/portable/raspberrypi/rp2040/rp2040_usb.c:143]: haven't read the spec, but this just smells wrong... toggle the PID IF the transfer is an odd number number of packets total?

**Review by kilograham — COMMENTED** [review]
not sure i you meant to leave all the extra logging stuff in there?

File: src/portable/raspberrypi/rp2040/rp2040_usb.c (hunk 1 above)
Comment (hathach) [reply src/portable/raspberrypi/rp2040/rp2040_usb.c:143]: Yup, the Data Toggle (PID) is toggled every packet. Following is the scheduling 108 bytes with endpoint with max packet size = 8. 
- Buffer 0 will start with 64 then 44 as last buf
- 64 is 8 packets starting with DATA1, each packet, DT toggled which mean after 8 packet, it is still DATA1. i.e at the 9th packet  (start of 44 bytes, transaction 87 in capture), the DT should remain the same (DATA1).

image

Comment (hathach) [reply src/portable/raspberrypi/rp2040/rp2040_usb.c:143]: PS: The log is there is on purpose, since I want to work more with rp2040 hcd/dcd, what I have in my mind is:
- Double buffering starting with host
- Make rp2040 common usb function more primitive, currently it handles also host and device specific code, making it more difficult to fix specific issue with either host/device (like above). Also it makes it difficult to follow in my taste.
- Host and device mode should be able to both enabled, and dynamically run depending on what the software want e.g using ID pin and/or VBUS sense to detect whether we attached to peer as host/device to initialize the correct mode.

Comment (kilograham) [reply src/portable/raspberrypi/rp2040/rp2040_usb.c:143]: my question was whether the code was correct - as far as i can see the packet_count is only dependent on the total transfer size, and therefore does change), or is ep->transfer_size the size per packet?

**Comment by kilograham** [comment]
note i'd like to pull this into the pico-0.10.0 branch anyway which we'll ship SDK1.2.0 with most likely

File: src/portable/raspberrypi/rp2040/rp2040_usb.c (hunk 1 above)
Comment (hathach) [reply src/portable/raspberrypi/rp2040/rp2040_usb.c:143]: I don't quite understand your question could you give an example with above total transfer size = 108 bytes above to elaborate.  Here is how the transfer size is determined https://github.com/hathach/tinyusb/blob/host-rp2040/src/portable/raspberrypi/rp2040/rp2040_usb.c#L189

**Comment by hathach** [comment]
> note i'd like to pull this into the pico-0.10.0 branch anyway which we'll ship SDK1.2.0 with most likely

no problem, I could release this as 0.10.1 , there is also issue when using pico reading msc thumbdrive as well. I will try to look at when I got time.

File: src/portable/raspberrypi/rp2040/rp2040_usb.c (hunk 1 above)
Comment (hathach) [reply src/portable/raspberrypi/rp2040/rp2040_usb.c:143]: I will try to explain as much as I could, as above example total transfer = 108 on endpoint with size = 8, which is broken into 2 sub transfers, both on buffer0 since we don't support double buffer just yet. 
- xfer1: transfer size = 64, start with DATA1, packet count = 8 
- xfer2: transfer size = 44, also start with DATA1, packet count = 5

if there is ever another xfer on the endpoint, it will start with DATA0 since the packet count is odd. Total transfer is broken in to 2 sub transfer size and therefore already taken into account when computing the next PID after this total transfer is complete. Hope that make sense, else I am happy to hear from your example.

File: src/portable/raspberrypi/rp2040/rp2040_usb.c [hunk 2]
```diff
@@ -126,8 +126,30 @@ void _hw_endpoint_start_next_buffer(struct hw_endpoint *ep)
...
+
+      if ( packet_count & 0x01 )
```
Comment (kilograham) [inline src/portable/raspberrypi/rp2040/rp2040_usb.c:145]: I guess to be clear, this was the line i was actually complaining about (based on the above).... for the the packets where packet_count is 8 the pid won't toggle, for all the ones packet count is 5 it will.

Comment (hathach) [reply src/portable/raspberrypi/rp2040/rp2040_usb.c:145]: I see what you mean there, you suspect that all the 8 packets of first 64 bytes has the same PID right ?

Comment (kilograham) [reply src/portable/raspberrypi/rp2040/rp2040_usb.c:145]: correct

Comment (liamfraser) [reply src/portable/raspberrypi/rp2040/rp2040_usb.c:145]: Looking at the trace above the DATA PID in low speed mode needs to be toggled every 8 bytes. It depends on the approach. You can either limit the ep->transfer_size to do several 8 byte transfers. OR you can start a 64 byte transfer in low speed mode and the hardware will flip the PID for you every 8 bytes.

Comment (hathach) [reply src/portable/raspberrypi/rp2040/rp2040_usb.c:145]: > correct

That isn't the case here, the controller is very smart to toggle the PID every packet as shown in the captured which is actual capture to develop this PR. We only need to write the correct initial PID. 

> You can either limit the ep->transfer_size to do several 8 byte transfers. OR you can start a 64 byte transfer in low speed mode and the hardware will flip the PID for you every 8 bytes.

I tried both way, both works. Actually the code used to limit transfer_size at 8 (max packet size), but having it with as 64 make it much more faster, this will also help to enable the double buffering later on as well.

Comment (liamfraser) [reply src/portable/raspberrypi/rp2040/rp2040_usb.c:145]: @kilograham do you agree this is resolved if the hardware toggles the pid every 8 bytes in LS mode?

**Review by liamfraser — APPROVED** [review]
Looks good to me assuming @kilograham agrees the Low Speed DATA PID conversation is resolved.

**Comment by hathach** [comment]
> Looks good to me assuming @kilograham agrees the Low Speed DATA PID conversation is resolved.

The PID is toggled by hardware as captured in analyzer. without the fix, it will trigger the incorrect PID `USB_INTS_ERROR_DATA_SEQ_BITS` error. Thank for the review, I will merge this since I have another PR pending since yesterday.

File: src/portable/raspberrypi/rp2040/rp2040_usb.c (hunk 2 above)
Comment (hathach) [reply src/portable/raspberrypi/rp2040/rp2040_usb.c:145]: actually this is only tested with IN transfer, therefore the PID is toggled from the device side. I haven't tested the OUT transfer where host controller is the one responsible for PID toggle. Though there is not many control transfer that has large payload > 64. We can keep this in mind, should it be an issue in the future.

**Review by kilograham — COMMENTED** [review]
ah, ok; "the code may be wrong, but fixes the problem at hand" :-) I'm cool with it for now!

File: src/portable/raspberrypi/rp2040/rp2040_usb.c (hunk 2 above)
Comment (hathach) [reply src/portable/raspberrypi/rp2040/rp2040_usb.c:145]: > well i'm still extremely confused by the code... at least a comment is needed... i'm still not clear why you toggle the packet every buffer (and indeed whether that is a 8 byte buffer or not) when the total packet length is odd. what if there are 4 packets?

I have explained it very clearly as above. PID flipped every packet per USB specs, 4 wont flip it

**Comment by hathach** [comment]
> ah, ok; "the code may be wrong, but fixes the problem at hand" :-) I'm cool with it for now!

The code is spot on and there is no maybe afaik. Please provide example or hands on test case if you are still in doubt.
