### PR TITLE
fix #2444 and other small things

### LINKED ISSUE #2444: CH34x ch34x_set_line_coding() bug
### Operating System

Linux

### Board

-

### Firmware

-

### What happened ?

`ch34x_set_line_coding()` handles user_data in wrong way:
```
    if (user_data) {
      user_data = result;
    }
```
correct is:
```
    if (user_data) {
      *((xfer_result_t*) user_data) = result;
    }
```
I'll create PR soon

### How to reproduce ?

-

### Debug Log as txt file (LOG/CFG_TUSB_DEBUG=2)

-

### Screenshots

_No response_

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

### PR DESCRIPTION
**Pull request by IngHK**
- fix #2444 and other small things:
- one `inline` change
- simplified TU_VERIFY and TU_ASSERT
- implemented open TODO check xfer->result
- added check upper baudrate limit

now tests of all CH34x on my desk are finished

### CODE REVIEW

**Review by hathach — APPROVED** [review]
look great, thank you. The build failed due to unrelated change by ESP IDF

File: src/class/cdc/cdc_host.c [hunk 1]
```diff
@@ -1513,8 +1514,7 @@ static void ch34x_process_config(tuh_xfer_t* xfer) {
   uintptr_t const state = xfer->user_data;
   uint8_t buffer[2]; // TODO remove
   TU_ASSERT (p_cdc,);
-
-  // TODO check xfer->result
+  TU_ASSERT (xfer->result == XFER_RESULT_SUCCESS,);
```
Comment (hathach) [inline src/class/cdc/cdc_host.c:1517]: note we still need to call config complete to continue enumerating other device. Will do that as follow up later.
