### PR TITLE
Fix NCM state on restart

### LINKED ISSUE #3436: NCM interface stop transmitting packets after ifconfig down+up on Linux side (STM32H7 DWC2)
### Operating System

Linux

### Commit SHA

3af1bec

### Board

Custom stm32h747 board

### Firmware

Custom stm32h747 board, but the problematic code is very similar to net_lwip_webserver with NCM config.
Alpine Linux 3.23 on the host side.

### What happened ?

When the system run for the first time, everything is fine.

Configuration:
```
#define CFG_TUD_NCM_IN_NTB_N		2
#define CFG_TUD_NCM_IN_NTB_MAX_SIZE	2048
#define CFG_TUD_NCM_OUT_NTB_N		2
#define CFG_TUD_NCM_OUT_NTB_MAX_SIZE	2048
```

1. Start the net_lwip_webserver-similar TinyUSB device.
2. On linux, after eth1 comes up, do `ifconfig eth1 up` and `dhcpcd eth1`
3. At this point, eth1 gets an IP address (given by TinyUSB dhcpd server), and the interface can be pinged, all is fine.
4. Run `ifconfig eth1 down` on the Linux side.
5. At this point, Linux stop listening to the INTERRUPT and BULK endpoints.
6. Run `ifconfig eth1 up` on the Linux side.
7. At this point, Linux is again listening to the INTERRUPT and BULK endpoints.
8. Observe that eth1 does not get an IP address anymore, because the TinyUSB device stop transmitting anything.

If I plug the debugger at this point, I notice that both `xmit_free_ntb` are null, but `xmit_tinyusb_ntb` is non null and `xmit_ready_ntb[0]` is non null (see image below), therefore `tud_network_can_xmit()` return false.

Image

I've tried with and without DMA it makes no difference.

Anyway, I would love to have some help/idea/suggestion at this point, I'm stuck.

### How to reproduce ?

See above.

### Debug Log as txt file (LOG/CFG_TUSB_DEBUG=2)

The following log starts at point 3) above, i.e. when everything is fine:

[tinyusb.log](https://github.com/user-attachments/files/24356930/tinyusb.log)

We can see at the end of the log, after the last `ifconfig eth1 up` that Linux sends `DHCP Discover` packets continuously, they get received by TinyUSB but generates no answer.

### Screenshots

_No response_

### I have checked existing issues, discussion and documentation

- [x] I confirm I have checked existing issues, discussion and documentation.

### PR DESCRIPTION
**Pull request by HiFiPhile**
- Fixed notification state handling so that when the interface is deactivated and reactivated, the link state update notification is correctly sent. Fix #3436

- Refactored both `recv_ready_ntb` and `xmit_ready_ntb` buffers in `ncm_interface_t` to use circular buffers, adding head, tail, and count fields for each, replacing the previous linear search and memmove approach.

### CODE REVIEW

**Comment by HiFiPhile** [comment]
@ceedriic how's it doing on your Mac ?

**Comment by ceedriic** [comment]
> @ceedriic how's it doing on your Mac ?

It works much better with the USB power supply fixed :)
Il will retest with/without the patch on different OSes, hopefully this week. Sorry for the delay.

**Comment by ceedriic** [comment]
> @ceedriic how's it doing on your Mac ?

Ok, I redid the tests with TinyUSB from 1 week ago, and with or without the one-liner fix here:

https://github.com/hathach/tinyusb/pull/3438/changes/fef11cd4451f0f9c6e5bf5b5f2c067a9c54b1216

I see no difference with or without this patch unfortunately. The following examples are all with the patch applied.

When I plug my fixed board board in, most of the time I get an IP address, but sometime not.

Here is when I didn't get an IP address:

```
Cedrics-MacBook-Pro:~ cedric$ ifconfig en26
en26: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=404<VLAN_MTU,CHANNEL_IO>
	ether 78:a6:83:00:00:00
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (none)
	status: inactive
```

And here is when I get one:


```
en26: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=404<VLAN_MTU,CHANNEL_IO>
	ether 78:a6:83:00:00:00
	inet6 fe80::10eb:16d9:fc48:6530%en26 prefixlen 64 secured scopeid 0x18 
	inet 192.168.2.245 netmask 0xfffffff8 broadcast 192.168.2.247
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (10baseT/UTP <full-duplex>)
	status: active
```

That's I guess the same problem that I and other other people have reported with the iPad.

Note that even when DHCP fails, the RUNNING flag is still here.

Now, If I try to bring the interface down and up:

```
Cedrics-MacBook-Pro:~ cedric$ sudo ifconfig en26 down
Cedrics-MacBook-Pro:~ cedric$ ifconfig en26
en26: flags=8822<BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 1500
	options=404<VLAN_MTU,CHANNEL_IO>
	ether 78:a6:83:00:00:00
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (none)
	status: inactive
Cedrics-MacBook-Pro:~ cedric$ sudo ifconfig en26 up
Cedrics-MacBook-Pro:~ cedric$ ifconfig en26
en26: flags=8823<UP,BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 1500
	options=404<VLAN_MTU,CHANNEL_IO>
	ether 78:a6:83:00:00:00
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (none)
	status: inactive
```

Then nothing works and the RUNNING flag is not set.

So there is still something fishy here.

I've tried with a regular usb-ethernet interface, and it works fine after up/down: both the RUNNING flag and DHCP work.

```
Cedrics-MacBook-Pro:~ cedric$ ifconfig en38
en38: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=404<VLAN_MTU,CHANNEL_IO>
	ether 00:e0:4c:69:62:5c
	inet6 fe80::180a:37ca:e3b6:4d4e%en38 prefixlen 64 secured scopeid 0x23 
	inet6 2a02:121f:5b49:0:10be:de20:724a:b2dd prefixlen 64 autoconf secured 
	inet6 2a02:121f:5b49:0:a8b5:d922:431c:d9cf prefixlen 64 autoconf temporary 
	inet 192.168.1.102 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (1000baseT <full-duplex>)
	status: active
Cedrics-MacBook-Pro:~ cedric$ sudo ifconfig en38 down
Cedrics-MacBook-Pro:~ cedric$ ifconfig en38 
en38: flags=8822<BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 1500
	options=404<VLAN_MTU,CHANNEL_IO>
	ether 00:e0:4c:69:62:5c
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (none)
	status: inactive
Cedrics-MacBook-Pro:~ cedric$ sudo ifconfig en38 up
Cedrics-MacBook-Pro:~ cedric$ ifconfig en38 
en38: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=404<VLAN_MTU,CHANNEL_IO>
	ether 00:e0:4c:69:62:5c
	inet6 fe80::180a:37ca:e3b6:4d4e%en38 prefixlen 64 secured scopeid 0x23 
	inet6 2a02:121f:5b49:0:10be:de20:724a:b2dd prefixlen 64 autoconf secured 
	inet6 2a02:121f:5b49:0:30fa:524a:d33c:fd30 prefixlen 64 autoconf temporary 
	inet 192.168.1.102 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (1000baseT <full-duplex>)
	status: active
```

I've also tried again to connect the TinyUSB NCM interface to Apline Linux 3.23 in a Mac VM:

```
alpine323:~# uname -a
Linux alpine323 6.18.13-0-lts #1-Alpine SMP PREEMPT_DYNAMIC 2026-02-20 15:23:57 aarch64 GNU/Linux
```

And when I connect the USB:

```
alpine323:~# dmesg
[  127.173790] usb 1-2: new full-speed USB device number 2 using xhci_hcd
[  127.305449] usb 1-2: New USB device found, idVendor=203a, idProduct=fffe, bcdDevice= 1.01
[  127.305455] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  127.305456] usb 1-2: Product: Virtual USB1.1 HUB
[  127.305457] usb 1-2: Manufacturer: Parallels
[  127.305457] usb 1-2: SerialNumber: PW3.0
[  127.306973] hub 1-2:1.0: USB hub found
[  127.307019] hub 1-2:1.0: 15 ports detected
[  127.588969] usb 1-2.1: new full-speed USB device number 3 using xhci_hcd
[  127.683548] usb 1-2.1: New USB device found, idVendor=0483, idProduct=4003, bcdDevice= 1.00
[  127.683553] usb 1-2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  127.683554] usb 1-2.1: Product: SL-3011
[  127.683555] usb 1-2.1: Manufacturer: Precidata
[  127.683555] usb 1-2.1: SerialNumber: 10419
[  127.694614] cdc_acm 1-2.1:1.0: ttyACM0: USB ACM device
[  127.694625] usbcore: registered new interface driver cdc_acm
[  127.694626] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters
[  127.696747] usbcore: registered new interface driver cdc_ether
[  127.732376] cdc_ncm 1-2.1:1.2: MAC-Address: 78:a6:83:00:00:00
[  127.732500] cdc_ncm 1-2.1:1.2 eth1: register 'cdc_ncm' at usb-0000:00:03.0-2.1, CDC NCM (NO ZLP), 78:a6:83:00:00:00
[  127.732518] usbcore: registered new interface driver cdc_ncm
[  127.733668] usbcore: registered new interface driver cdc_wdm
[  127.734434] usbcore: registered new interface driver cdc_mbim
```

Note the "(NO ZLP)" message, I don't know if that's something to be worried about.

I need to "UP" the interface manually on Alpine:

```
alpine323:~# ifconfig eth1
eth1      Link encap:Ethernet  HWaddr 78:A6:83:00:00:00  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
alpine323:~# ifconfig eth1 up
alpine323:~# ifconfig eth1
eth1      Link encap:Ethernet  HWaddr 78:A6:83:00:00:00  
          inet6 addr: fe80::7aa6:83ff:fe00:0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:726 (726.0 B)
```

And then start dhcp manually:

```
alpine323:~# dhcpcd eth1
dhcpcd-10.3.0 starting
DUID 00:01:00:01:30:e1:9c:ed:78:a6:83:00:00:00
eth1: IAID 83:00:00:00
eth1: soliciting an IPv6 router
eth1: soliciting a DHCP lease
eth1: offered 192.168.2.245 from 192.168.2.241
eth1: probing address 192.168.2.245/29
eth1: leased 192.168.2.245 for 86400 seconds
eth1: adding route to 192.168.2.240/29
alpine323:~# ifconfig eth1
eth1      Link encap:Ethernet  HWaddr 78:A6:83:00:00:00  
          inet addr:192.168.2.245  Bcast:192.168.2.247  Mask:255.255.255.248
          inet6 addr: fe80::7aa6:83ff:fe00:0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:23 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1088 (1.0 KiB)  TX bytes:2150 (2.0 KiB)

```

At this point, if I bring the interface down and up, the interface goes back as "RUNNING", but DHCP does not work anymore:

```
alpine323:~# ifconfig eth1 down
alpine323:~# ifconfig eth1
eth1      Link encap:Ethernet  HWaddr 78:A6:83:00:00:00  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:23 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1088 (1.0 KiB)  TX bytes:2150 (2.0 KiB)

alpine323:~# ifconfig eth1 up
alpine323:~# ifconfig eth1
eth1      Link encap:Ethernet  HWaddr 78:A6:83:00:00:00  
          inet6 addr: fe80::a3de:288e:f357:571a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:29 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1088 (1.0 KiB)  TX bytes:2958 (2.8 KiB)

alpine323:~# ifconfig eth1
eth1      Link encap:Ethernet  HWaddr 78:A6:83:00:00:00  
          inet6 addr: fe80::a3de:288e:f357:571a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:37 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1088 (1.0 KiB)  TX bytes:3998 (3.9 KiB)

alpine323:~# ifconfig eth1
eth1      Link encap:Ethernet  HWaddr 78:A6:83:00:00:00  
          inet addr:169.254.113.244  Bcast:169.254.255.255  Mask:255.255.0.0
          inet6 addr: fe80::a3de:288e:f357:571a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:41 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1088 (1.0 KiB)  TX bytes:4494 (4.3 KiB)
```

I don't know what to make of all that.

Cedric

**Comment by HiFiPhile** [comment]
I feel like something shady is going on, with this PR on my Windows PC and Arch laptop Nucleo-U5A5/H747-DISCO boards work very well the 1st plug or link up/down by ip command or board button.

Could you try H747-DISCO with net lwip example ? If the initial connection doesn't work, what about wakeup button toggle ?

I've added a board button fix.

**Comment by ceedriic** [comment]
> I feel like something shady is going on, with this PR on my Windows PC and Arch laptop Nucleo-U5A5/H747-DISCO boards work very well the 1st plug or link up/down by ip command or board button.

Well, I just tried on one of my FreeBSD server and it works well there too:

```
ugen1.2: <Precidata SL-3011> at usbus1
ubt1 on uhub0
ubt1: <MediaTek Inc. WirelessDevice, class 239/2, rev 2.10/1.00, addr 1> on usbus0
ubt1: ubt_attach:680: could not get two interfaces
device_attach: ubt1 attach returned 6
umodem0 on uhub1
umodem0: <Precidata SL-3011, class 239/2, rev 2.00/1.00, addr 1> on usbus1
umodem0: data interface 1, has no CM over data, has break
cdce0 on uhub1
cdce0: <Precidata SL-3011, class 239/2, rev 2.00/1.00, addr 1> on usbus1
ubt1 on uhub0
ubt1: <MediaTek Inc. WirelessDevice, class 239/2, rev 2.10/1.00, addr 1> on usbus0
ubt1: ubt_attach:680: could not get two interfaces
device_attach: ubt1 attach returned 6
ue0: <USB Ethernet> on cdce0
ue0: Ethernet address: 78:a6:83:00:00:00
[root@antennae ~]# ifconfig ue0
ue0: flags=8802<BROADCAST,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=80000<LINKSTATE>
	ether 78:a6:83:00:00:00
	media: Ethernet autoselect
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
[root@antennae ~]# ifconfig ue0 up
[root@antennae ~]# ifconfig ue0
ue0: flags=1008843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST,LOWER_UP> metric 0 mtu 1500
	options=80000<LINKSTATE>
	ether 78:a6:83:00:00:00
	media: Ethernet autoselect
	status: active
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
[root@antennae ~]# dhclient ue0
DHCPDISCOVER on ue0 to 255.255.255.255 port 67 interval 7
DHCPOFFER from 192.168.2.241
DHCPREQUEST on ue0 to 255.255.255.255 port 67
DHCPACK from 192.168.2.241
bound to 192.168.2.245 -- renewal in 43200 seconds.
[root@antennae ~]# ifconfig ue0
ue0: flags=1008843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST,LOWER_UP> metric 0 mtu 1500
	options=80000<LINKSTATE>
	ether 78:a6:83:00:00:00
	inet 192.168.2.245 netmask 0xfffffff8 broadcast 192.168.2.247
	media: Ethernet autoselect
	status: active
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
[root@antennae ~]# ifconfig ue0 down
[root@antennae ~]# ifconfig ue0
ue0: flags=8802<BROADCAST,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=80000<LINKSTATE>
	ether 78:a6:83:00:00:00
	inet 192.168.2.245 netmask 0xfffffff8 broadcast 192.168.2.247
	media: Ethernet autoselect
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
[root@antennae ~]# ifconfig ue0 up
[root@antennae ~]# ifconfig ue0
ue0: flags=1008843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST,LOWER_UP> metric 0 mtu 1500
	options=80000<LINKSTATE>
	ether 78:a6:83:00:00:00
	inet 192.168.2.245 netmask 0xfffffff8 broadcast 192.168.2.247
	media: Ethernet autoselect
	status: active
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
```

So there is something special with the Mac.

Note that I'm working on full-speed only, and I guess not many people use an ethernet adapter with full-speed these days... I wonder if there is a bug in MacOS at low speed?

> 
> Could you try H747-DISCO ? If the initial connection doesn't work, what about wakeup button toggle ?
> 

Yes, but not before middle of week-end, I'm about to leave and travel to Sion to visit a customer there.

However, in 10 days I'll be near Lyon :)

**Comment by ceedriic** [comment]
Ok, there are problems on the Mac (see issue #3505) but this patch fix a real problem at least on Windows and should be applied IMHO.

File: src/class/net/ncm_device.c [hunk 1]
```diff
@@ -940,6 +976,9 @@ bool netd_control_xfer_cb(uint8_t rhport, uint8_t stage, tusb_control_request_t
           if (ncm_interface.itf_data_alt == 1) {
             tud_network_recv_renew_r(rhport);
             notification_xmit(rhport, false);
+          } else {
+            // Reset notification state to send link state update when interface is re-activated
+            ncm_interface.notification_xmit_state = NOTIFICATION_CONNECTED;
```
Comment (hathach) [inline src/class/net/ncm_device.c]: @HiFiPhile  should we reset to NOTIFICATION_SPEED instead of NOTIFICATION_CONNECTED. I got claude suggestion below

````
  NCM spec ch.7.1 mandates that CONNECTION_SPEED_CHANGE must be sent before NETWORK_CONNECTION. Both notifications are required, in that order.

  All major implementations confirm this:

  ┌───────────────────────┬────────────────────────────┬─────────────────────────────────────────────────────────────────────────────┐
  │    Implementation     │   On alt=1 reactivation    │                                 Reset state                                 │
  ├───────────────────────┼────────────────────────────┼─────────────────────────────────────────────────────────────────────────────┤
  │ Linux gadget f_ncm.c  │ Resets to NCM_NOTIFY_SPEED │ Full sequence (speed → connected)                                           │
  ├───────────────────────┼────────────────────────────┼─────────────────────────────────────────────────────────────────────────────┤
  │ Zephyr usbd_cdc_ncm.c │ Resets to IF_STATE_INIT    │ Full sequence, with comment: "Speed change must be sent first, chapter 7.1" │
  ├───────────────────────┼────────────────────────────┼─────────────────────────────────────────────────────────────────────────────┤
  │ Linux host cdc_ncm.c  │ Expects both               │ Comment cites spec ch.7.1                                                   │
  ├───────────────────────┼────────────────────────────┼─────────────────────────────────────────────────────────────────────────────┤
  │ macOS                 │ Requires both              │ Won't do DHCP without NETWORK_CONNECTION preceded by speed                  │
  └───────────────────────┴────────────────────────────┴─────────────────────────────────────────────────────────────────────────────┘

  What this means for the PR

  The fix at line 978 should change from:

  ncm_interface.notification_xmit_state = NOTIFICATION_CONNECTED;

  to:

  ncm_interface.notification_xmit_state = NOTIFICATION_SPEED;

  And additionally, when itf_data_alt == 1 (reactivation), the state should also be reset to NOTIFICATION_SPEED before calling notification_xmit(), so the full sequence is sent on every
  reactivation — matching Linux and Zephyr behavior. The current code at line 941-942 calls notification_xmit() but doesn't reset the state, so if the previous cycle completed
  (NOTIFICATION_DONE), nothing gets sent.
```

Comment (HiFiPhile) [reply src/class/net/ncm_device.c]: Right, I've also updated tud_network_link_state
